server:
  port: 8080
spring:
  application:
    name: client-app

  cloud:
    openfeign:
      client:
        config:
          viaCepClient:
            connectTimeout: 1000
            readTimeout: 500
            loggerLevel: BASIC
  sql:
    init:
      continue-on-error: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: senha123
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 0
      maximum-pool-size: 15
      connection-timeout: 3000
      idle-timeout: 300000
      max-lifetime: 600000
      initialization-fail-timeout: -1
      validation-timeout: 1000
  jpa:
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

url:
  viacep.host: https://viacep.com.br/ws

#  spring.cloud.openfeign.client.config.default.connectTimeout=5000
#  spring.cloud.openfeign.client.config.default.readTimeout=5000
#  spring.cloud.openfeign.client.config.default.loggerLevel=full
#  spring.cloud.openfeign.client.config.default.errorDecoder=org.springframework.cloud.openfeign.FeignClientUsingPropertiesTests.DefaultErrorDecoder
#  spring.cloud.openfeign.client.config.default.retryer=org.springframework.cloud.openfeign.FeignClientUsingPropertiesTests.NoRetryer
#  spring.cloud.openfeign.client.config.default.dismiss404=true